routes/web.php
<?php

use function Ramsey\Uuid\v1;
use GuzzleHttp\Psr7\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//controllerm原版寫法 //8的用法
Route::get('/controller', [HomeController::class, 'home']);






Route::get('/', function () {
    return view('home.index');
})->name('home.index')->middleware('auth');

//上面簡化來的  這樣不會麻煩 只是單純回傳view就這樣 前提不用傳參數或其他工作
// Route::view('/', 'home.index')->name('home.index')->middleware('auth');


$contact = [
    1 => [
        'title' => '1111',
        'content' => 'bbb',
        'new_b' => true,
        'has_true' => true,
    ],
    2 => [
        'title' => '222w',
        'content' => 'c',
        'new_b' => false,
    ],
];

Route::get('/contact', function () use ($contact) {

    // compact($contact) == ['contact'=>$contact]
    return view('contact.index', ['contact' => $contact]);
})->middleware('auth.basic');

//use() 使用未定義 的var
Route::get('/contact/{id}', function ($id) use ($contact) {

    // ***重點 當你有錯誤 傳入的陣列
    //回傳404 錯誤 當你上架東西不能讓別人看到錯誤只能出現不存在
    // abort_if 函式會在給定布林表達式的結果為 ture 時，回應一件 HTTP 例外

    abort_if(!isset($contact[$id]), 404);

    return view('contact.show', ['contact' => $contact[$id]]);
})->name('contact.show');



// 基本給參數
// 參數funtion內的亂寫 一樣可以接到 路徑的參數

// where()設條件 給限制 這樣才不會一直跑去controller執行
//如果要全域限制RouteServiceProvider去 找boot()涵式

// Route::get('/posts/{id}', function ($id) {
//     return 'hey' . $id;
// });
//     // ->where([
//     //     'id' => '[0-9]+'
//     // ])
//     ->name('posts.show');







// $id給預設值
Route::get('/uses/{id?}', function ($id = 2) {
    return 'hey' . $id;
})->name('users.show');



//自定義用
Route::get('/fun/response', function () use ($contact) {
    return response($contact, 201)
        ->header('content-Type', 'application/json')
        ->cookie('My_cookie', 'danie', 3600);
});


// 返回特定 HTTP 302
Route::get('/fun/redirect', function () {
    return redirect('....');
});
// 回上一個
Route::get('/fun/back', function () {
    return back();
});

// 返回 並傳回id是 users.show就需要傳入的參數
Route::get('/fun/name_route', function () {
    return redirect()->route('users.show', ['id' => 1]);
});
//重新導向 一個網站
Route::get('/fun/away', function () {
    return redirect()->away('https://google.com');
});


//json
Route::get('/fun/json', function () use ($contact) {
    return response()->json($contact);
});

//下載東西
Route::get('/fun/download', function () use ($contact) {
    return response()->download(public_path('/daniel.jpg'), 'face.jpg');
});

Route::get('/request', function (Request $request) use ($contact) {
    dd(request()->all());
});
Route::resource('/test', 'TestController');
Route::resource('/posts', 'PostsController');
    // ->only('index', 'show', 'create', 'store', 'edit','update');
//只用那些
//禁用那些
// Route::resource('posts', 'PostsController')->except('index', 'show');


//facebook
Route::get('login/facebook', 'Auth\LoginController@redirectToProvider');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback');

//github
Route::get('login/github', 'Auth\LoginController@github');
Route::get('login/github/callback', 'Auth\LoginController@githubCallback');

Auth::routes();


//artisan 
Route::get('artisan',function(){
    Artisan::call('migrate:reset'); 
    return 1;
});

resources/views/layout/tep.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {{-- //用mix 混和會把版本壓縮 然後webpack可以改如何混和 設定黨 --}}
  <link rel="stylesheet" href="{{ mix('css/app.css') }}">
  <script src="{{ mix('js/app.js') }}" defer></script>
  <title>Document @yield('title') </title>
</head>

<body>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-white border-botton shadow-sm mb-3">
    <h5 class="ny-0 mr-md-auto font-weight-normal">Laravel App</h5>
    <nav class="my-2 my-md-0 mr-md-3">
      <a class="p-2 text-dark" href="{{ route('home.index') }}">Home</a>
      {{-- <a class="p-2 text-dark" href="{{ route('contact.show') }}">Contacnt</a> --}}
      <a class="p-2 text-dark" href="{{ route('posts.index') }}">Blog Post</a>
      <a class="p-2 text-dark" href="{{ route('posts.create') }}">Add Blog</a>


      @guest
        @if (Route::has('register'))
          <a class="p-2 text-dark" href="{{ route('register') }}">regiser</a>
        @endif
        <a class="p-2 text-dark" href="{{ route('login') }}">login</a>

      @else
        <a class="p-2 text-dark" href="{{ route('logout') }}" id=""
        onclick="event.preventDefault(); document.getElementById('logout-form').submit();"
        >logout ({{ Auth::user()->name }})</a>


        <form action="{{ route('logout') }}" method="POST" style="display:none;" id="logout-form">
                @csrf
        </form>
      @endguest
    </nav>
  </div>

  <div class="container">
    @if (session('status'))
      <div class="alert alert-success">{{ session('status') }}</div>
    @endif
    @yield('content')
  </div>
</body>

</html>